config/routes.rb
Rails.application.routes.draw do
  
  root to: 'home#index'
  # resources :searches
  devise_for :users
  resources :venues
  resources :gigs
  resources :schedules do 
    resources :bookings
  end
  
  resources :genres
  # resources :users


end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many  :gigs
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  
  before_action :authenticate_user!
  load_and_authorize_resource

  before_action :set_genre, only: [:show, :edit, :update, :destroy]

  def index
    if params[:name]
    @genres = Genre.where("name like ?", "%#{params[:name]}%")
    else
    @genres = Genre.all
    end
  end

  def show
  end

  def new
    @genre = Genre.new
  end

 
  def edit
  end

  def create
    @genre = Genre.new(genre_params)
  end

  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to @genre, notice: 'Genre was successfully updated.' }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url, notice: 'Genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_genre
    @genre = Genre.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/views/genres/_form.html.erb
<%= form_for(@genre) do |f| %>

  <div style="width: 500px">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/genres/_genre.html.erb
<nav style="padding: 20px;">
  <p><strong>Genre name: <%= genre.name%> </strong></p>

  <ul>
    <li><%= button_to('Show', genre_path(genre), method: :get)%></li>
    <li><%= button_to('Edit', edit_genre_path(genre), method: :get)%></li>
    <li><%= button_to('Delete genre', genre_path(genre), method: :delete, data:{confirm: 'Delete the genre? Are you sure?'})%></li>
  </ul>
</nav>

app/views/genres/edit.html.erb
<h1>Editing Genre</h1>

<%= render 'form' %>

app/views/genres/index.html.erb
<div>
  <h2><strong><%= link_to 'Add New Genre', new_genre_path %></strong></h2>
</div><p id="notice"><%= notice %></p>

<h1>Listing Genres</h1>

<%= render @genres %>

app/views/genres/new.html.erb
<h1>New Genre</h1>

<%= render 'form' %>

app/views/genres/show.html.erb
<p>
  <strong>Genre :</strong>
  <%= @genre.name %>
</p>

<p><strong>Gigs:</strong><br>
  <% @genre.gigs.each do |gig| %>
    <%= gig.try(:name) %><br>
  <% end %>
</p>

<strong><%= link_to 'Edit', edit_genre_path(@genre) %></strong>
<strong><%= link_to 'Back', genres_path %></strong>