config/routes.rb
Rails.application.routes.draw do
  
  root to: 'home#index'
  # resources :searches
  devise_for :users
  resources :venues
  resources :gigs
  resources :schedules do 
    resources :bookings
  end
  
  resources :genres
  # resources :users


end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to  :venue
  belongs_to  :gig
  has_many  :bookings
  has_many :users, :through => :bookings

  def human_readable_date
    schedule.strftime("%A, %d %b %Y %I:%M %p")
  end

  def schedule_not_exist_at_venue?(venue_id)
    # Checking if any gig already present withhin +_ 3 HOURS on same day
    duration = 3
    Schedule.where(venue_id: venue_id).all? {|s| s.schedule != self.schedule} && !Schedule.where(venue_id: venue_id).all? {|s| ((s.schedule.strftime("%H").to_i - duration)..(s.schedule.strftime("%H").to_i + duration)).include?(self.schedule.strftime("%H").to_i)} 
    # binding.pry


    
    # after_duration = (s.schedule + (duration/24.0)).strftime("%H:%M")
    # after_duration = s.schedule.strftime("%H").to_i + duration
    # before_duration = s.schedule.strftime("%H").to_i - duration

    # before_duration = (s.schedule - (duration/24.0)).strftime("%H:%M")
    # (before_duration..after_duration).include?(self.schedule.strftime("%H:%M"))
  end

  def number_of_seat_available
    capacity = venue.seat
    total_booking = Booking.where(schedule_id: id).count
    number_of_seat_available = capacity - total_booking
  end

  def seat_availability
    number_available = number_of_seat_available
    venue.seat >= number_available
  end

  def search_result(name)
    gig_matches = Gig.where("name like ?", "%#{name}%")
    venue_matches = Venue.where("name like ?", "%#{name}%")
      # binding.pry
    schedule_gig = gig_matches.map {|gig| Schedule.where(:gig_id => gig.id) }
    schedule_venue = venue_matches.map {|venue| Schedule.where(:venue_id => venue.id) }
    ((schedule_gig + schedule_venue).flatten).uniq
  end


end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  
  before_action :authenticate_user!
  
  load_and_authorize_resource
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  def index
    if params[:name]
      @schedule = Schedule.new
      @schedules = @schedule.search_result("#{params[:name]}")
        # binding.pry
    else
      @schedules = Schedule.all
      @bookings = Booking.where(user_id: current_user.id)
    end
  end

  def show
  end

  def new
    @schedule = Schedule.new
  end

  def edit
  end

  def create
    @schedule = Schedule.new(schedule_params)
    if @schedule.schedule_not_exist_at_venue?(@schedule.venue_id)
      respond_to do |format|
        if @schedule.save
          format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
          format.json { render :show, status: :created, location: @schedule }
        else
          format.html { render :new }
          format.json { render json: @schedule.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_path, alert: "Venue has already been booked" 
    end
  end


  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
  def set_schedule
    @schedule = Schedule.find(params[:id])
  end
  
  def schedule_params
    params.require(:schedule).permit(:gig_id, :venue_id, :schedule, :user_ids=>[])
  end

end

app/views/schedules/_form.html.erb
<%= form_for(@schedule) do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :venue_id %><br>
    <%= f.collection_select(:venue_id, Venue.all, :id, :name) %>
  </div>

  <div class="field">
    <%= f.label :gig_id %><br>
    <%= f.collection_select(:gig_id, Gig.all, :id, :name) %>
  </div>

  <div class="field">
    <%= f.label :schedule %><br>
    <%= f.datetime_select :schedule %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schedules/_schedule.html.erb
<div class="container">
  <div class="listing-all">
  <p><strong>Gig Name:</strong><%= schedule.gig.try(:name) %></p>
  <p><strong> Venue Name: </strong> <%= schedule.venue.try(:name) %></p>
  <p><strong>Schedule: </strong><%= schedule.human_readable_date %></p>
  
  <ul style="transform: skewX(-25deg)">
    <li><%= button_to('Show', schedule_path(schedule), method: :get)%></li>
    <li><%= button_to('Edit', edit_schedule_path(schedule), method: :get) if can? :manage, Schedule %></li>
    <li><%= button_to('Delete', schedule_path(schedule), method: :delete, data:{confirm: 'Delete the schedule? Are you sure?'}) if can? :delete, Schedule %></li>
    <!-- <p class="alert"> <%= alert %> </p> -->
  </ul><br>

</div>

</div>

app/views/schedules/edit.html.erb
<h1>Editing Schedule</h1>

<%= render 'form' %>

app/views/schedules/index.html.erb
<div class="add-link-option">
  <%= link_to 'New Schedule', new_schedule_path if can? :manage, Schedule%>
</div>

<%= render @schedules %>

<% if @bookings %>
<div class="listing-all">
  <h2>Your bookings</h2>

  <% @bookings.each do |b| %>
  <p><%= b.schedule.gig.try(:name) %></p>
  <p><%= b.schedule.human_readable_date %></p>
  <p><%= link_to "Show Booking", schedule_booking_path(b.schedule_id, b.id) %></p>
  <% end %>
<% end %>

</div>

app/views/schedules/new.html.erb
<h1>New Schedule</h1>

<%= render 'form' %>

app/views/schedules/show.html.erb
<br>
<div class="listing-all">
  <p><strong>Gig: </strong><%= @schedule.gig.try(:name) %></p>

  <p><strong>Venue: </strong><%= @schedule.venue.try(:name) %></p>

  <p><strong>Schedule: </strong><%= @schedule.human_readable_date %></p>
  <br>

  <div class="menu">
    <ul>
      <li><strong><%= link_to 'Back', schedules_path %></strong></li>
      <li><strong><%= link_to 'Book This', new_schedule_booking_path(@schedule) %></strong></li>
    </ul>
  </div>

</div>