config/routes.rb
Rails.application.routes.draw do
  
  root to: 'home#index'
  # resources :searches
  devise_for :users
  resources :venues
  resources :gigs
  resources :schedules do 
    resources :bookings
  end
  
  resources :genres
  # resources :users


end

app/models/venue.rb
class Venue < ActiveRecord::Base
  has_many :schedules 
  has_many :gigs, through: :schedules
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController

  load_and_authorize_resource
  before_action :authenticate_user!

  before_action :set_venue, only: [:show, :edit, :update, :destroy]


  def index
    if params[:name]
    @venues = Venue.where("name like ?", "%#{params[:name]}%")
    else
    @venues = Venue.all
    end
  end

  def show
  end

  def new
    @venue = Venue.new
    @gigs = Gig.new
  end

  def edit
    @gigs = Gig.new
  end

  def create
    @venue = Venue.new(venue_params)

    respond_to do |format|
      if @venue.save
        format.html { redirect_to @venue, notice: 'Venue was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end


  def update
    respond_to do |format|
      if @venue.update(venue_params)
        format.html { redirect_to @venue, notice: 'Venue was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end


  def destroy
    @venue.destroy
    respond_to do |format|
      format.html { redirect_to venues_url, notice: 'Venue was successfully destroyed.' }
    end
  end

  private
  def set_venue
    @venue = Venue.find(params[:id])
  end

  def venue_params
    params.require(:venue).permit(:name, :address, :seat, :gig_ids=>[])
  end
end

app/views/venues/_form.html.erb
<div class="container">
  <%= form_for(@venue) do |f| %>
  <% if @venue.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@venue.errors.count, "error") %> prohibited this venue from being saved:</h2>
    <ul>
      <% @venue.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div><br>


  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div><br>

  <div class="field">
    <%= f.label :seat %>
    <%= f.text_field :seat %>
  </div>

  <p>Choose your Gig:</p>
  <div >
    <%= collection_check_boxes(:venue, :gig_ids, Gig.all, :id, :name) %>
  </div><br>

  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>
</div>

app/views/venues/_venue.html.erb
<div class="container">
  <div class="listing-all">
    <nav style="padding: 20px;">
      <p><strong>Venue Name: </strong><%= venue.name%></p>

      <p><strong>Venue Address: </strong><%= venue.address%></p>

      <p><strong>Venue Seat Capacity: </strong><%= venue.seat%></p>

      <ul style="transform: skewX(-25deg)">
        <li><%= button_to('Show', venue, method: :get)%></li>
        <li><%= button_to('Edit', edit_venue_path(venue), method: :get) if can? :manage, Venue %></li>
        <li><%= button_to('Delete venue', venue_path(venue), method: :delete) if can? :delete, Venue %></li>
      </ul>
    </nav>
  </div>
</div>

app/views/venues/edit.html.erb
<h1>Editing Venue</h1>

<%= render 'form' %>

app/views/venues/index.html.erb
<div class="add-link-option">
  <h1><strong><%= link_to 'Add New Venue', new_venue_path if can? :manage, Venue%></strong></h1>
</div>
<div class="listing"><h1>Listing Venues</h1></div>

<%= render @venues %>

app/views/venues/new.html.erb
<h1>New Venue</h1>

<%= render 'form' %>

app/views/venues/show.html.erb
<div class="listing-all">
  <p><strong>Venue Name:</strong><%= @venue.name %></p>

  <p><strong>Address:</strong><%= @venue.address %></p>

  <p><strong>Seat Number:</strong><%= @venue.seat %></p>

  <p><strong>Schedules and Gigs: </strong><br>
    <% @venue.schedules.each do |schedule| %>
    <%= schedule.schedule %>
    <%= schedule.gig.try(:name) %><br>
    <% end %></p><br>
    
    <div class="menu">
      <ul>
        <li><strong><%= link_to 'Edit', edit_venue_path(@venue) if can? :manage, Venue %></strong></li>
        <li><strong><%= link_to 'Back', venues_path %></strong></li>
      </ul>
    </div>
  </div>