config/routes.rb
Rails.application.routes.draw do
  
  root to: 'home#index'
  # resources :searches
  devise_for :users
  resources :venues
  resources :gigs
  resources :schedules do 
    resources :bookings
  end
  
  resources :genres
  # resources :users


end

app/models/gig.rb
class Gig < ActiveRecord::Base
  belongs_to  :genre
  has_many :schedules 
  has_many :venues, through: :schedules

  mount_uploader :gig_image, GigImageUploader
  
end

app/controllers/gigs_controller.rb
class GigsController < ApplicationController

  load_and_authorize_resource

  before_action :authenticate_user!

  before_action :set_gig, only: [:show, :edit, :update, :destroy]




  def index
    if params[:name]
      @gigs = Gig.where("name like ?", "%#{params[:name]}%")
    else
      @gigs = Gig.all
    end
  end

  def show
    @schedules = Schedule.where(gig_id: params[:id])
  end

  def new
    @gig = Gig.new
    @venues = Venue.new
  end

  def edit
    @venues = Venue.new
  end

  def create
    @gig = Gig.new(gig_params)

    respond_to do |format|
      if @gig.save
        format.html { redirect_to @gig, notice: 'Gig was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end


  def update
    respond_to do |format|
      if @gig.update(gig_params)
        format.html { redirect_to @gig, notice: 'Gig was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end


  def destroy
    @gig.destroy
    respond_to do |format|
      format.html { redirect_to gigs_url, notice: 'Gig was successfully destroyed.' }
    end
  end


  private
  def set_gig
    @gig = Gig.find(params[:id])
  end

  def gig_params
    params.require(:gig).permit(:name, :description, :genre_id, :gig_image, :venue_ids=>[])
  end
end

app/views/gigs/_form.html.erb
<div class="container">
  <%= form_for(@gig) do |f| %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div><br>

  <div class="field">
    <%= f.label :gig_image %>
    <%= f.file_field :gig_image %>
  </div><br>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div><br>

  <div class="field">
    <%= f.label :genre_id %>
    <%= f.select("genre_id", Genre.all.map {|c| [c.name, c.id]}, {prompt: 'Select Genre'}, html_options = {}) %>
  </div>
  <br>

  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>


</div>

app/views/gigs/_gig.html.erb
<!-- <div style="transform: skewX(-15deg); transform: translate(5px,5px)" class="container avatarBox .text_center"> -->
<div class="container avatarBox .text_center">

  <div class="listing-all">

    <p><strong>Gig Name: </strong><%= gig.name%></p>

    <p><strong>Genre: </strong> <%= gig.genre.try :name %></p>
    <p><%= image_tag gig.gig_image.medium.url %></p>
  
    <p>
      <%= button_to('Show', gig, method: :get)%>
      <%= button_to('Edit', edit_gig_path(gig), method: :get) if can? :manage, Gig %>
      <%= button_to('Delete gig', gig_path(gig), method: :delete, data:{confirm: 'Delete the gig? Are you sure?'}) if can? :delete, Gig %>
    </p>
  </div>
</div>

app/views/gigs/edit.html.erb
<h1>Editing Gig</h1>

<%= render 'form' %>

app/views/gigs/index.html.erb
<div class="listing"> <h1>Listing Gigs</h1> </div>

<div class="add-link-option">
  <%= link_to 'Add New Gig', new_gig_path if can? :manage, Gig%>
</div>


<%= render @gigs %>

app/views/gigs/new.html.erb
<h1>New Gig</h1>

<%= render 'form' %>

app/views/gigs/show.html.erb
<div class="listing-all">
  <p><strong>Gig Name:</strong><%= @gig.name %></p>

  <p><%= link_to image_tag(@gig.gig_image.medium.url) %>
  </p>

  <p><strong>Genre:</strong><%= @gig.genre.try(:name) %></p>

  <p><strong>Description:</strong><%= @gig.description %></p>

  <p>
    <strong>Schedules and Venues: </strong><br>
    <% @schedules.each do |schedule| %>
    <%= schedule.human_readable_date %>
    <%= schedule.venue.try(:name) %><br>
    <% end %>
  </p>

  <div class="menu">
    <ul>
    <li><strong><%= link_to 'Edit', edit_gig_path(@gig) if can? :manage, Gig  %></strong></li>
    <li><strong><%= link_to 'Back', gigs_path %></strong></li>
    </ul>

  </div>

</div>